### ISSUE TITLE
Error running ./ run.rb

### ISSUE THREAD

**Issue by lummyare** [calabash/x-platform-example#5]
Hi just cloned the x-platform project example and did a bundler update and it was fine.

But i tried running ./run.rb and bundler exec cucumber -p ios and its given me this:

lummy:x-platform-example seunare$ ./run.rb ios
Bundler version 1.9.2
Using the ios profile...
Feature: Initial experience
  As a user I want a helpful and simple initial
  experience with the app. I should be able to get help
  and login to an existing WordPress site.

  @info @reinstall
  Scenario: Obtaining more information         # features/login.feature:7
undefined method `extend_world' for nil:NilClass (NoMethodError)
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/multi_test-0.1.1/lib/multi_test.rb:31:in `extend_with_best_assertion_library'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/lib/cucumber/rb_support/rb_language.rb:121:in `extend_world'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/lib/cucumber/rb_support/rb_language.rb:67:in `begin_rb_scenario'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/lib/cucumber/rb_support/rb_language.rb:101:in `begin_scenario'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/lib/cucumber/language_support/language_methods.rb:14:in `before'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/lib/cucumber/runtime/support_code.rb:112:in `block in fire_hook'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/lib/cucumber/runtime/support_code.rb:111:in `each'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/lib/cucumber/runtime/support_code.rb:111:in `fire_hook'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/lib/cucumber/runtime.rb:107:in `before'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/lib/cucumber/runtime.rb:98:in `before_and_after'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/lib/cucumber/runtime.rb:82:in `block in with_hooks'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/lib/cucumber/runtime/support_code.rb:120:in `call'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/lib/cucumber/runtime/support_code.rb:120:in `block (3 levels) in around'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/lib/cucumber/language_support/language_methods.rb:9:in `block in around'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/lib/cucumber/language_support/language_methods.rb:97:in `call'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/lib/cucumber/language_support/language_methods.rb:97:in `execute_around'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/lib/cucumber/language_support/language_methods.rb:8:in `around'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/lib/cucumber/runtime/support_code.rb:119:in `block (2 levels) in around'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/lib/cucumber/runtime/support_code.rb:123:in `call'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/lib/cucumber/runtime/support_code.rb:123:in `around'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/lib/cucumber/runtime.rb:94:in `around'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/lib/cucumber/runtime.rb:81:in `with_hooks'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/lib/cucumber/ast/tree_walker.rb:13:in `execute'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/lib/cucumber/ast/scenario.rb:32:in `block in accept'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/lib/cucumber/ast/scenario.rb:79:in `with_visitor'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/lib/cucumber/ast/scenario.rb:31:in `accept'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/lib/cucumber/ast/tree_walker.rb:58:in `block in visit_feature_element'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/lib/cucumber/ast/tree_walker.rb:170:in `broadcast'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/lib/cucumber/ast/tree_walker.rb:57:in `visit_feature_element'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/lib/cucumber/ast/feature.rb:38:in `block in accept'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/lib/cucumber/ast/feature.rb:37:in `each'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/lib/cucumber/ast/feature.rb:37:in `accept'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/lib/cucumber/ast/tree_walker.rb:27:in `block in visit_feature'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/lib/cucumber/ast/tree_walker.rb:170:in `broadcast'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/lib/cucumber/ast/tree_walker.rb:26:in `visit_feature'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/lib/cucumber/ast/features.rb:28:in `block in accept'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/lib/cucumber/ast/features.rb:17:in `each'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/lib/cucumber/ast/features.rb:17:in `each'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/lib/cucumber/ast/features.rb:27:in `accept'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/lib/cucumber/ast/tree_walker.rb:21:in `block in visit_features'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/lib/cucumber/ast/tree_walker.rb:170:in `broadcast'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/lib/cucumber/ast/tree_walker.rb:20:in `visit_features'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/lib/cucumber/runtime.rb:49:in `run!'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/lib/cucumber/cli/main.rb:47:in `execute!'
/Users/seunare/.rvm/gems/ruby-2.2.0/gems/cucumber-1.3.18/bin/cucumber:13:in `<top (required)>'
/Users/seunare/.rvm/gems/ruby-2.2.0/bin/cucumber:23:in `load'
/Users/seunare/.rvm/gems/ruby-2.2.0/bin/cucumber:23:in `<main>'
/Users/seunare/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/Users/seunare/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'

**Comment by bosnian** [comment]
I'm also having similar issue, it seems that case is that signature of .ipa file is not right.

**Comment by jrmhaig** [comment]
I get this error with Ruby 2.2 and later. However, the tests work with Ruby 2.1 which, incidentally, is no longer officially supported apart from security updates.
